### ISSUE TITLE
make fails if no .git

### ISSUE THREAD

**Issue by danilobuerger** [krallin/tini#10]
If `.git` directory is not present the command

```
execute_process (COMMAND git log -n 1 --date=local --pretty=format:"%h" WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}" OUTPUT_VARIABLE tini_VERSION_GIT)
```
in CMakeLists.txt will fail with

> fatal: Not a git repository (or any of the parent directories): .git

causing `TINI_GIT` to not get set. Causing this error:

```
/home/build/src/tini-0.6.0/src/tini.c: In function 'print_usage':
/home/build/src/tini-0.6.0/src/tini.c:84:80: error: expected expression before ')' token
  fprintf(file, "%s (version %s - %s)\n", basename(name), TINI_VERSION, TINI_GIT);
                                                                                ^
CMakeFiles/tini.dir/build.make:54: recipe for target 'CMakeFiles/tini.dir/src/tini.c.o' failed
make[2]: *** [CMakeFiles/tini.dir/src/tini.c.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/tini.dir/all' failed
make[1]: *** [CMakeFiles/tini.dir/all] Error 2
Makefile:136: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by krallin** [comment]
Hey there,

Seems like this should be an easy fix, I'll have a look. 

I'm curious though; in which situation would you use this? 

Cheers,

**Comment by danilobuerger** [comment]
Building from source ;-)
```
wget https://github.com/krallin/tini/archive/v0.6.0.tar.gz
tar
cmake
make
```

**Comment by danilobuerger** [comment]
Docker image to build tini for alpine (musl libc):
https://github.com/feastr/docker-image-build-tini

**Comment by krallin** [comment]
Do you want to try the proposed fix in #12?

(I'm on mobile right now so I can't really test it outside of CI, without git)

**Comment by danilobuerger** [comment]
Yes, works for my build. However the output of ``tini`` is then rather unsexy:
> tini (version 0.6.0 - )

**Comment by krallin** [comment]
@danilobuerger, 

Fixed this in #13. I also changed the format of the version string a little bit to indicate it's coming from git.

**Comment by danilobuerger** [comment]
Nice

**Comment by danilobuerger** [comment]
Updated the apk package as well:
https://github.com/feastr/docker-image-build-tini/releases/tag/0.7.0

**Comment by krallin** [comment]
Looks great @danilobuerger; thanks for maintaining that : )
