### ISSUE TITLE
Why tini will produce a lot of the same process, and turn off

### ISSUE THREAD

**Issue by penhauer-xiao** [krallin/tini#105]
Why tini will produce a lot of the same process, and turn off, whether to sleep 1 second or 500 milliseconds; as the red is the production process and exit
![image](https://user-images.githubusercontent.com/6280121/34667404-cdb00a82-f4a3-11e7-8d5b-d04b4e52ba4e.png)

From the process ID, docker-init was created by tini 6 times, and finally only the process ID is 5 alive.
![image](https://user-images.githubusercontent.com/6280121/34667488-2be3f5fa-f4a4-11e7-9dac-349694ede8c4.png)

![image](https://user-images.githubusercontent.com/6280121/34667424-db6f621c-f4a3-11e7-8341-3ca44acbff52.png)

**Comment by krallin** [comment]
There isn't enough information for me to help you here. What is `/opt/monit/bin/docker-init`? Where does it come from?

**Comment by SkeLLLa** [comment]
In htop by the default userland threads colored in green. So there are 3 processes and others (colored in green) are threads. So that not "a lot of same processes".

**Comment by penhauer-xiao** [comment]
@krallin  Docker-init is my own program, named docker-init

**Comment by penhauer-xiao** [comment]
@SkeLLLa  I still don't understand

**Comment by krallin** [comment]
Tini started your `docker-init` program once, but your `docker-init` program is running 6 threads. That's why you see it 6 times.

**Comment by penhauer-xiao** [comment]
@krallin I finally understand, thank you
