### ISSUE TITLE
Way to make tini clean up docker exec child processes

### ISSUE THREAD

**Issue by matthewlenz** [krallin/tini#111]
I've been playing around with docker run vs docker exec and cleaning up processes when the docker run/exec process is terminated.

docker run --name some_container -i --init some_image some_parent_that_spawns_long_running_child
kill -s SIGTERM <docker run's pid>
**The result is the child processes are cleaned up by tini.**

docker run --name some_container -di --init some_image
docker exec -i some_container some_parent_that_spawns_long_running_child
kill -s SIGTERM <docker exec's pid>
**The result is the child processes are not cleaned up by tini**

Any thoughts on how tini could be used to help with this situation?

**Comment by krallin** [comment]
I'm afraid there isn't much Tini can do here: when you do `docker exec`, the exec'd process is *not* a child of Tini in the container , which means it's not part of Tini's process reaping hierarchy... which means it never gets reparented to Tini. Indeed, the process is a child of the `docker-containerd-shim` process:

```
root      2063  0.1  0.0 2330952 23676 ?       Ssl  21:15   0:06  \_ docker-containerd --config /var/run/docker/containerd/containerd.toml
root      9978  0.1  0.0   8576  3396 ?        Sl   22:20   0:00      \_ docker-containerd-shim -namespace moby -workdir /var/lib/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/41d990b4495747a343e41f2c3b73cc069f761a713282b8ec16ffc306ded504a1 -address /var/run/docker/containerd/docker-containerd.sock -containerd-binary /usr/bin/docker-containerd -runtime-root /var/run/docker/runtime-runc
root      9996  0.0  0.0   1048     4 pts/0    Ss   22:20   0:00          \_ /dev/init -- bash
root     10051  0.0  0.0  22016  3696 pts/0    S+   22:20   0:00          |   \_ bash
root     10840  0.1  0.0  21952  3632 pts/1    Ss   22:23   0:00          \_ bash
root     10855  0.0  0.0   5928   672 pts/1    S+   22:23   0:00              \_ sleep 12345
```

(in the above, PID 10840 is the `docker exec` session) 

That said, after some quick testing, I'm observing that any "abandoned" children of the `docker exec` session seem to be SIGKILL'd. Are you observing something different? How are you monitoring for processes "not cleaned up by Tini"? Do you have e.g. some `ps auxwww --forest` output I could look at?

**Comment by zousheng** [comment]
@matthewlenz maybe you should try tini subreaping method, eg: docker run -i container /dev/init -s -- bash or yourscript, this way it will reparent your command and script to tini thougt it's not pid 1, but it works.

**Comment by matthewlenz** [comment]
@zousheng @krallin 

Doesn't really seem to matter how I 'run' the container.  When I use exec it always creates a new shim process:

```
root      1846     1  0 Mar06 ?        00:29:46 /usr/bin/dockerd -H fd://
root      8823  1846  0 Mar06 ?        00:16:24  \_ docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --metrics-interval=0 --start-timeout 2m --state-dir 
root     24304  8823  0 07:02 ?        00:00:00      \_ docker-containerd-shim 65d1edbe2dc2b01d17eb1557d7db8e3bbb6256834d134d5339fd4d5f6b8fef32 /var/run/docker/libcontainerd/65d1edbe2dc
root     24323 24304  0 07:02 ?        00:00:00      |   \_ /dev/init -- /dev/init -s -- bash
root     24365 24323  0 07:02 ?        00:00:00      |       \_ /dev/init -s -- bash
root     24366 24365  0 07:02 ?        00:00:00      |           \_ bash
root     24583  8823  0 07:04 ?        00:00:00      \_ docker-containerd-shim 65d1edbe2dc2b01d17eb1557d7db8e3bbb6256834d134d5339fd4d5f6b8fef32 /var/run/docker/libcontainerd/65d1edbe2dc
root     24601 24583  0 07:04 ?        00:00:00          \_ sleep 6000
```

If I kill the `docker exec` process the shim `24583` still dangles around.

Btw, the reason I'm wanting to use exec instead of run is because the setup/init time of a run command is too slow for my purposes.  exec on the other hand is nearly as fast as running a command natively.

**Comment by krallin** [comment]
I'm really not sure there is much I can do to help here — Tini isn't in your `docker exec`'d session's process hierarchy, so there's no way for Tini to ever reap the daemons left behind there. I'd recommend opening an issue with Docker instead, here.

**Comment by matthewlenz** [comment]
@krallin one question and then I'll stop bugging you.  how did you get your docker exec to use the same shim parent process as the docker run?

**Comment by krallin** [comment]
No problem — unfortunately, that's just how it worked for me, I didn't do anything special here. I'lm using docker `17.12.1-ce` and containerd `v1.0.1 9b55aab90508bd389d7654c4baf173a981477d55`, perhaps you're using a different version on your end?

**Comment by matthewlenz** [comment]
Same versions here.   I see you are using a namespace of moby in your shim.  When researching signaling with regards to docker exec there are bugs on both the docker issue tracker and the moby issue tracker.  I wonder if maybe they've worked around this issue?
