### ISSUE TITLE
Should tini run as root?

### ISSUE THREAD

**Issue by haani-niyaz** [krallin/tini#113]
I am trying to understand the implications of running tini as `root` inside the container. From what I understand init systems run as `root` however I was hoping to get some clarification on running tini as a non-root user (if possible) considering running processes inside the container as `root` is generally considered to be bad practice.

I hope my question is clear, thanks.

**Comment by krallin** [comment]
You can run Tini as whatever user you'd like: it doesn't need to run as root.

The only thing you should avoid is running Tini as a non-root user to start a setuid binary (such as `sudo`): if you did so, Tini wouldn't be able to send signals to the process it started.
