### ISSUE TITLE
cannot find rcrt1.o

### ISSUE THREAD

**Issue by rquackenbush** [krallin/tini#116]
I'm attempting to build tini from source during a [YOCTO](https://www.yoctoproject.org/) build. I'm getting this error:

```
/home/richquackenbush/boondocks-build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/tini/0.14.0-r0/recipe-sysroot-native/usr/bin/arm-poky-linux-gnueabi/../../libexec/arm-poky-linux-gnueabi/gcc/arm-poky-linux-gnueabi/7.3.0/ld: cannot find rcrt1.o: No such file or directory
```

Is there an obvious dependency I'm missing?

**Comment by krallin** [comment]
Can you provide more detail regarding how you're building Tini here? With what you provided, there isn't much to go on unfortunately.

**Comment by krallin** [comment]
My guess here is that you're trying to do a static build, which probably doesn't play very well in an environment like Yocto that already manages a lot of the build environment.

**Comment by rquackenbush** [comment]
Ahh - this does appear to be a YOCTO related issue. I'm able to build tini fine outside of that environment. Thanks for the clue!

**Comment by krallin** [comment]
:+1:
