### ISSUE TITLE
What's the recommended way of running tini

### ISSUE THREAD

**Issue by adrianog** [krallin/tini#119]
Hi thanks for the excellent resource.
If I have a recent docker installation what's the best way to use tini? Through the --init flag? I wouldn't need to derive from the tini base images if I do that, or will I?

**Comment by krallin** [comment]
Using the `--init` flag is indeed a good approach if your Docker installation supports it and you're confident that you'll be able to set it when you needed. If you do that, then indeed you don't need to install Tini in your own image or use an image that includes Tini.

**Comment by krallin** [comment]
Using `--init`, you get `tini (pid 1) -> ENTRYPOINT (pid x) + CMD`

**Comment by tohtor** [comment]
Thanks !
