### ISSUE TITLE
How can tini be used for POD  environment when the PID namespace is shared.

### ISSUE THREAD

**Issue by anannaya** [krallin/tini#120]
Hi,

I have a pod with 5 containers , each container has a entry point tini with subreaping.  I am bit confused here .. Could you please clarify is it possible to use tini in such a situation.  
Br,
Anand

**Comment by krallin** [comment]
I'm not sure how shared PID namespaces are implemented by your orchestrator (which I suspect is Kubernetes), so I can't really say for sure, but generally speaking, either of the two following options should avoid the creation of orphaned zombie processes:

- All your containers in the PID namespace have Tini running in subreaper mode as the entrypoint.
- PID 1 in the PID namespace is Tini (in subreaper mode or not - it doesn't matter).
