### ISSUE TITLE
not found tini in docker

### ISSUE THREAD

**Issue by hbakhtiyor** [krallin/tini#122]
i added this snippet of code in my dockerfile
```
# Add Tini
ENV TINI_VERSION v0.18.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /usr/bin/tini
RUN chmod +x /usr/bin/tini
ENTRYPOINT ["/usr/bin/tini", "--"]
```
but the tini not found in docker
```
/bin/sh: 1: [/usr/bin/tini,: not found
```

**Comment by krallin** [comment]
It looks like your `ENTRYPOINT` isn't getting properly interpreted. Indeed, you can see that `sh` is looking for a program called `[/usr/bin/tini,` (note the leading `[` and trailing `,`) which is basically `["/usr/bin/tini",` interpreted by a shell.

The Dockerfile snippet you provided here does however look correct.

Can you post your full Dockerfile and instructions to reproduce the issue?

Thanks.

**Comment by hbakhtiyor** [comment]
hi @krallin, the issue was in my dockerfile
before use `ENV` which not work (give the error), and now just pass the path string without env

`ENTRYPOINT ["/usr/bin/tini", "--", "/path/to/some/bin"]` 


```
# Add Tini
ENV TINI_VERSION v0.18.0
BIN_PATH /path/to/some/bin

ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /usr/bin/tini
RUN chmod +x /usr/bin/tini
ENTRYPOINT ["/usr/bin/tini", "--", ${BIN_PATH}]
```

**Comment by ktzsolt** [comment]
I've just hit a similar problem
```
FROM node:22-alpine

ENV TINI_VERSION=v0.19.0
ADD  --chown=nextjs:nodejs https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /usr/local/bin/tini
RUN chmod +x /usr/local/bin/tini

ENTRYPOINT ["/usr/local/bin/tini", "--"]
```

```
docker run --rm -it mytini:alpine date
exec /usr/local/bin/tini: no such file or directory
```

The problem is that for alpine images we must use the muslc built binary, that is tini-muslc-amd64
```
FROM node:22-alpine

ENV TINI_VERSION=v0.19.0
ADD  --chown=nextjs:nodejs https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-muslc-amd64  /usr/local/bin/tini
RUN chmod +x /usr/local/bin/tini

ENTRYPOINT ["/usr/local/bin/tini", "--"]
```

works fine:
```
docker run --rm -it mytini:alpine date
Tue Oct 14 14:12:43 UTC 2025
```
