### ISSUE TITLE
Key 595E85A6B1B4779EA4DAAEC70B588DFF0527A9B7 can't be retrieved

### ISSUE THREAD

**Issue by jryberg** [krallin/tini#131]
Hi,

There seems to be some kind of issue with the key:
> gpg --batch --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 595E85A6B1B4779EA4DAAEC70B588DFF0527A9B7
gpg: requesting key 0527A9B7 from hkp server p80.pool.sks-keyservers.net
gpgkeys: key 595E85A6B1B4779EA4DAAEC70B588DFF0527A9B7 can't be retrieved
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0

Doing a manual search and the key does not exist
http://p80.pool.sks-keyservers.net/pks/lookup?search=595E85A6B1B4779EA4DAAEC70B588DFF0527A9B7&fingerprint=on&op=index

> No results found
No results found: No keys found

**Comment by krallin** [comment]
Hi there,

See this issue: https://github.com/krallin/tini/issues/124

Note that the key does in fact exist: http://p80.pool.sks-keyservers.net/pks/lookup?search=0x595E85A6B1B4779EA4DAAEC70B588DFF0527A9B7&fingerprint=on&op=index

I’ve been personally observing more and more unreliability connecting to public keyservers, so if you’re incorporating this in  a build, I would recommend embedding the key in your source repository (this is also more secure). 

At the end of the day, this isn’t really something I control as the maintainer of Tini. The key’s publicly available, so ultimately it’s up to you as the end-user to decide how you’d like to retrieve it - the right solution will likely depend on your specific circumstances.
