### ISSUE TITLE
busybox won't run tini

### ISSUE THREAD

**Issue by geekodour** [krallin/tini#133]
I am not sure why this is happening, 
I mounted [`https://github.com/krallin/tini/releases/download/v0.18.0/tini`](https://github.com/krallin/tini/releases/download/v0.18.0/tini) to a volume and and `./tini` shows file not found when I am inside the mounted directory. 

The image I am using is : [`prom/busybox`](https://hub.docker.com/r/prom/busybox/dockerfile) which is `FROM`'ed from `busybox:uclibc`

Using kubernetes for managing the volumes and the containers:

Mounting:
```yaml
- name: executables
  mountPath: /executables
```

Volume creation:
```yaml
- name: executables
  emptyDir: {}
```
I ran a sidecar container that adds the `tini` binary to this volume.

inside the `/executables` directory after attaching to the main container:
```shell
/executables # ls
tini
/executables # pwd
/executables
/executables # ls
tini
/executables # ./tini 
sh: ./tini: not found
/executables # 
```

I've created a question at SO too: 

https://stackoverflow.com/questions/55524266/existing-binary-executable-not-found-inside-kubernetes-mounted-volume-in-docker

cc @krallin

**Comment by geekodour** [comment]
I'll try using `tiny-static`

**Comment by geekodour** [comment]
After trying with `tiny-static` , tini runs but then shows the executable tini is trying to run is not available. now the executable does run directly without tini. so it is existing and working. any idea?

**Comment by krallin** [comment]
Yeah, you do need the static version if you don’t have glibc installed, and
the dynamic linker’s error output is a bit questionable.

But it sounds like you solved that already! 👏

A few questions for the remaining problem:

- Can you share the exact command you’re using to run Tini? (Ideally with
the actual executable argument)
- Can you try building Tini locally and seeing if the locally compiled
version has the same problem?  Try both the static and dynamic versions
after building them.
- Can you run your container as privileged, install strace, then run
`strace -- tini-static PROGRAM -- ARGS` and share the output? Make sure to
review said output before sharing for any confidential information you
might not want to be publishing.

Thanks!
