### ISSUE TITLE
Make tini not exit the container if the first child exists but other 

### ISSUE THREAD

**Issue by geekodour** [krallin/tini#139]
There's a usecase where I wish tini kept the container running if atleast one of its direct child is running.

> When the "first" child process exits (/your/program in the examples above), Tini exits as well, with the exit code of the child process (so you can check your container's exit code to know whether the child exited successfully).
- from readme

I've tried double forking `sleep` inside the entrypoint script so that sleep becomes a child of PID 1, so now there are two children for PID 1 (entrypoint and sleep) but if in case entrypoint fails, tini exits and container exits.

Another attempt is this one:
```
ENTRYPOINT ["tini", "--", "sh", "-c","sleep 99999999& /usr/bin/clone.sh \"$@\"", "--"]
```
ps output:
```
root           1  0.0  0.0    204     4 ?        Ss   08:41   0:00 tini -- sh -c sleep 99999999& /usr/bin/clone.sh "$@" -- make deploy && touch /
root           8  0.0  0.0   1628  1024 ?        Ss   08:41   0:00 /bin/sh /usr/bin/clone.sh make deploy && touch /tmp/READY && echo 'deploy succeeded
root           9  0.0  0.0   1552     4 ?        S    08:41   0:00  \_ sleep 99999999
root          22  0.0  0.0   1140   768 ?        S    08:41   0:00  \_ make deploy
root         365  0.0  0.1 133652 29000 ?        Sl   08:45   0:00      \_ ./gke resource apply -a /etc/serviceaccount/service-account.json
```
^ Here `sh` is the direct child for tiny and `sleep` is running in background, still if `make deploy` crashes, container crashes. (why is it not waiting for sleep)

Can't we have tini stay alive till atleast it has one direct child?

**Comment by krallin** [comment]
Basically what @yosifkit  said — this isn't really the desired scope for Tini.

**Comment by mviereck** [comment]
I've stumbled over this, too.
I'd like tini to exit after all childs has gone.
Instead of watching all childs at the same time - isn't it possible to watch one single child only (as done yet), but if the child exits:
 - look if there are still childs of tini.
 - take the first one / an arbitrary one as the single child to look at.
 - exit if no childs are left.

**Comment by geekodour** [comment]
@mviereck  I actually solved this using supervisord, see this if you need some code example:
https://github.com/prometheus/prombench/pull/280
