### ISSUE TITLE
Back Porting Releases for s390x and ppc64le

### ISSUE THREAD

**Issue by james-crowley** [krallin/tini#142]
@krallin I was wondering if you would be willing to back “port” some of the releases for `s390x` and ` ppc64le`? Some projects I found are still using dated versions of Tini, like `v0.14.0` and `v0.15.0`, but no binaries exist for `s390x` and `ppc64le`. This makes it hard to get other open source projects to support `s390x` and `ppc64le` since now it requires them to add in the functionality of manually building Tini. 

Would you be willing to release the binaries and push them to the GitHub release page? The most dated version I saw was `v0.14.0`. So ideally, if you could push binaries for architectures at  `v0.14.0` and ` v0.15.0`, that would be amazing!

**Comment by krallin** [comment]
This would be non-trivial since the building code (and notably the cross-compiling bits) has evolved along with the rest of the versions. 

With regard to:

> This makes it hard to get other open source projects to support `s390x` and `ppc64le` since now it requires them to add in the functionality of manually building Tini.

Is upgrading to a newer version of Tini not an option? There haven't really ever been breaking changes in Tini, is there a reason to not simply update?

**Comment by james-crowley** [comment]
@krallin 

> Is upgrading to a newer version of Tini not an option? There haven't really ever been breaking changes in Tini, is there a reason to not simply update?

That totally works. Some projects are a little less then willing to update. But the guys over at https://github.com/ansible/awx/issues/4700, seem open to working with me. I'll just suggest updating Tini. 

Thanks for building for `s390x` and `ppc64le`! It helps everyone out with getting more applications to work on those platforms. 

Feel free to close out this issue if you want!
