### ISSUE TITLE
Provide concise documentation of tini's parameters 

### ISSUE THREAD

**Issue by jlusiardi** [krallin/tini#148]
Please put the defined parameters (from https://github.com/krallin/tini/blob/3c5368682eb238d2177bfef98f9ac4bbc28aa9a0/src/tini.c#L238 onwards) also in the README.md in a concise table.

Can ` -e EXIT_CODE` be repeated?

**Comment by krallin** [comment]
> Can -e EXIT_CODE be repeated?

It can, yes. I'll update the code to mention that.

As for putting those in the README — I'd rather keep it focused on practical examples. Running `--help` on the binary can get you all this info.

**Comment by jlusiardi** [comment]
Ok fine for me as well ;) thanks!
