### ISSUE TITLE
How to always use the latest release?

### ISSUE THREAD

**Issue by SVilgelm** [krallin/tini#151]
Hi,
I inherited a Dockerfile with
```Dockerfile
ADD https://github.com/krallin/tini/releases/download/v0.18.0/tini /sbin/tini
RUN chmod +x /sbin/tini
ENTRYPOINT ["/sbin/tini", "-vgs", "--"]
```

Everything works fine, except that I don't like that the version of the tini is pinned here.
So, Do you have a solution, how to always use the latest version of tini?

Thank you

**Comment by SVilgelm** [comment]
Forgot to say, I have an image based on centos/RH
So, if it possible to install the tini using `yum`

**Comment by krallin** [comment]
Hey there, this isn't something that's available, I'm sorry. This is also not something I'm looking to provide, since it effectively makes it impossible to include any breaking changes (not that I'm planning on any, but still).

**Comment by SVilgelm** [comment]
Hey, thank you for a clarification. Then we need to figure out how to automatically update it.

**Comment by ell1e** [comment]
@SVilgelm did you find a way to work around this? I have the same problem
