### ISSUE TITLE
Mislabeled PPC64LE Releases 

### ISSUE THREAD

**Issue by james-crowley** [krallin/tini#152]
I noticed on the releases the the PowerPC releases were named `tini-ppc64el`. This there any reason behind this?

When running on `ppc64le`, `uname` and other architecture identifiers return PowerPC as `ppc64le` not `ppc64el`. This naming confusion is causing problems with automation, since I usually just grab `uname -m` or `System.getProperty("os.arch")`, and form the URL for the download.

Like this:

```
ADD https://github.com/krallin/tini/releases/download/v0.18.0/tini-${tini_suffix} /tini
```

`${tini_suffix}` being the result I get back from  `uname -m` or `System.getProperty("os.arch")`.

Is there anyway you would be willing to change this?

**Comment by tianon** [comment]
(Not a maintainer here, just offering info)

`uname -m` is really unreliable for userspace architecture detection, especially when using `setarch`/`linux32` on a 64bit system, so I believe `tini` releases use `dpkg` architecture notation (`dpkg --print-architecture`), which should give you the architecture of your userspace environment instead of the architecture of your kernel.

**Comment by james-crowley** [comment]
@tianon I was mostly using `uname -m` as example. `dpkg --print-architecture` is good but not included by default in a lot of distros like CentOS or ClefOS. If I am not forgotten, I think you might need to install/enable epel which is not ideal. 

I am not sure there is a good solution since in most languages like Java or Go, when you use GO ARCH or do `os.arch` they return `ppc64le`. 

I want to avoid additional logic in build scripts or Dockerfiles with converting `ppc64le` to `ppc64el`.

**Comment by krallin** [comment]
Yeah, @tianon is basically spot on here with the reasoning behind why this is called the way it is. I wouldn't want to _change_ this, but I sounds like it might be reasonable to add aliases to what uname would return. I'll take a look.
