### ISSUE TITLE
Question, would tini work with grand-child processes?

### ISSUE THREAD

**Issue by nemo83** [krallin/tini#157]
Hi,

I have a particular scenario where my docker container launches a Jvm script that in turn launches my actual app. It looks something like:

`docker > jvm_app > actual_jvm_webserver`

Now I've tried to update the Jvm script to catch and forward the SIGTERM and wait for child process to gracefully terminates, but while I can update the launcher to catch the SIGTERM (I can clearly see in the logs), when I invoke the [.destroy ](https://www.scala-lang.org/api/current/scala/sys/process/Process.html#destroy():Unit) I think `SIGKILL` is sent instead. Anyway, main problem is that the actual implementation depends on the underlying implementation, so I just can rely on it.

I've also tested that the `actual_jvm_webserver` handles SIGTERM if I directly sent it its way... *SO*... my question is.

Can I use tini to handle this particular scenario? Any tips? Thanks in advance

**Comment by krallin** [comment]
You can add `-g` to your Tini args to have it signal all its subprocesses, so if you have `tini -> jvm_app -> actual_jvm_server`, then the latter 2 would receive signals sent to Tini. Be mindful Tini will only wait for `jvm_app` to exit before exiting itself and therefore terminating your container.
