### ISSUE TITLE
How to redirect logs to a file

### ISSUE THREAD

**Issue by deppfx** [krallin/tini#163]
I'm starting tini via a `startup.sh` in a docker container as shown below:
```exec /usr/bin/tini -s -- "$CMD"```

How can I redirect the output of the shell to a log file? I tried:
```exec /usr/bin/tini -s -- "${CMD[@]}" > /var/log/tini.log```
```exec /usr/bin/tini -s -- "${CMD[@]} > /var/log/tini.log"```
but both of them don't seem to work.

I feel like I'm missing something here.

**Comment by krallin** [comment]
Tini logs to stderr, so to redirect its logs you want `2> /var/log/tini.log`. You can also set `TINI_VERBOSITY=0` in your environment if you want no logs.
