### ISSUE TITLE
Why use ADD if fixed version in Dockerfile

### ISSUE THREAD

**Issue by raphaelauv** [krallin/tini#165]
Hello , the main example use the dockerfile command `ADD`

but if it's a fixed version like in the example why not use a `RUN` , so it do not re-evaluate at every build

replace
```bash
# Add Tini
ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
ENTRYPOINT ["/tini", "--"]
```

By
```bash
# Add Tini
ENV TINI_VERSION v0.19.0
RUN wget https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini  -O /tini
RUN chmod +x /tini
ENTRYPOINT ["/tini", "--"]
```

**Comment by yosifkit** [comment]
I would guess that the point of the `ADD` is to be universally applicable, many images don't have `curl` or `wget` by default.

(`curl` or `wget` would be a "best practices" option, since you can also verify and delete the gpg key and `.asc` in a single layer)

**Comment by tianon** [comment]
See also https://github.com/krallin/tini/issues/103 (which I'd argue this is probably technically a duplicate of).

**Comment by raphaelauv** [comment]
Thanks for your answers :+1:
