### ISSUE TITLE
Keep tini alive when killing the main child process

### ISSUE THREAD

**Issue by gionapaolini** [krallin/tini#168]
I am working on a developer environment that runs directly on kubernetes.

I need to be able to kill and start again the main process, but to be able to do so I need a way of keeping tini alive when I send the kill command to the child.

Is it possible with the current implementation?

**Comment by yosifkit** [comment]
> All Tini does is spawn a single child [...], and wait for it to exit

If the child exits, `tini` exits.  You likely need to use a "full" process supervisor (`supervisord`, `systemd`, etc) (or fairly complex script) or have a way for the application to "reload" without exiting (like nginx does with `SIGHUP`).

**Comment by gionapaolini** [comment]
Alright thanks, I'll close this issue.
