### ISSUE TITLE
tini now in alpine aports

### ISSUE THREAD

**Issue by danilobuerger** [krallin/tini#18]
http://git.alpinelinux.org/cgit/aports/commit/testing?id=894f561562b47fc67e496800fe6a04261a7613a0

I will be closing my repository and maintain the aport in the official repository. Just an fyi here.

**Comment by krallin** [comment]
This looks great; thanks @danilobuerger! 

I'd like to add it to the README since a package manager is a better installation method than `curl` (!), but I'm not too familiar with Alpine Linux. How would one go about using Alpine's package manager to install Tini now that it's in the repos?

Cheers,

**Comment by danilobuerger** [comment]
Sure. The simplest one liner would probably be
```
# apk add --update --repository http://dl-4.alpinelinux.org/alpine/edge/testing/ tini
```

1. `apk` is the package manager
2. `add` installs a package
3. `--update` updates the index before installing to actually find packages
4. `--repository <url>` adds the url as repository to index (in this case edge testing)
5. `tini` installs the package tini

Another solution would be:

```
# echo "@testing http://dl-4.alpinelinux.org/alpine/edge/testing/" >> /etc/apk/repositories 
# apk add --update tini@testing
```

**Comment by krallin** [comment]
Updated the README; thanks again for packaging Tini @danilobuerger! : )

**Comment by danilobuerger** [comment]
No problem :-)
