### ISSUE TITLE
sks-keyservers.net is not maintained anymore, need to update install instruction

### ISSUE THREAD

**Issue by kenhys** [krallin/tini#184]
# The problem

sks-keyservers.net is not maintained anymore, need to update install instruction.

# Expected

https://github.com/krallin/tini#signed-binaries section is up-to-date by using another keyserver.

# Actual

```
$ gpg --batch --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 595E85A6B1B4779EA4DAAEC70B588DFF0527A9B7 
gpg: keyserver receive failed: No name
```

The above command always fails.

This is because this service is not maintained anymore, see https://sks-keyservers.net/ about this announcement.
![image](https://user-images.githubusercontent.com/225841/122854505-c6bb3700-d34e-11eb-84b7-0c50f95b848d.png)

**Comment by madsonic** [comment]
this note in the readme is a potential workaround, have not tried it.

>NOTE: If you are using Docker 1.13 or greater, Tini is included in Docker itself. This includes all versions of Docker CE. To enable Tini, just pass the --init flag to docker run.

also stated in the docker docs.
https://docs.docker.com/engine/reference/run/#specify-an-init-process

**Comment by baylisscg** [comment]
You can switch to Ubuntu's keyserver `hkp://keyserver.ubuntu.com:80` which currently works.

**Comment by baylisscg** [comment]
Should work fine under Docker however if you're building for other situations, say Kubernetes, having it in the container is required.

> this note in the readme is a potential workaround, have not tried it.
> 
> > NOTE: If you are using Docker 1.13 or greater, Tini is included in Docker itself. This includes all versions of Docker CE. To enable Tini, just pass the --init flag to docker run.
> 
> also stated in the docker docs.
> https://docs.docker.com/engine/reference/run/#specify-an-init-process

**Comment by krallin** [comment]
https://github.com/krallin/tini/pull/188 will fix this. Do also note that you can also make this work offline by downloading the key for this fingerprint and importing it locally (i.e. without a server)
