### ISSUE TITLE
prctl(PR_SET_PDEATHSIG, ...) should be called after fork(), not before

### ISSUE THREAD

**Issue by igor-anferov** [krallin/tini#213]
From the [official Linux documentation](https://man7.org/linux/man-pages/man2/prctl.2.html):
```
The parent-death signal setting is cleared for the child of a fork(2).
```
So, calling `prctl(PR_SET_PDEATHSIG, ...)` before `spawn()`, which is currently the case, doesn't make sense.

**Comment by krallin** [comment]
The commit that introduced this explains the use case:

https://github.com/krallin/tini/commit/eb0f6de3a5efc57bba81992ad8463494a6f45c4a

Their goal was indeed to signal Tini when its parent dies, not to signal
Tini’s child when Tini dies.

**Comment by igor-anferov** [comment]
Aaah, I see, thanks for your explanation. But I still don't understand the last phrase from the commit message:
```
    $ unshare --pid --fork setpriv --reuid user tini -s -p SIGKILL -- <prog>

As soon as unshare is getting killed, tini will get signalled SIGKILL
and exit as well, tearing down <prog> with it.
```
Why would <prog> be torn down in this case?

**Comment by krallin** [comment]
When you’re in a PID namespace and PID1 in that namespace exits the rest of
the namespace will be killed too

**Comment by igor-anferov** [comment]
Got it, thank you!
