### ISSUE TITLE
tini not running as child subreaper on AWS Lambda

### ISSUE THREAD

**Issue by samkit-jain** [krallin/tini#218]
I have a Docker image that I have running on AWS Lambda and in that I am not able to run tini as a subreaper. It fails with the following error upon startup
```
[FATAL tini (9)] Failed to register as child subreaper: Operation not permitted
```

In my Dockerfile, I have installed tini as 
```dockerfile
FROM public.ecr.aws/lambda/python:3.10
# ... code here
ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
RUN export TINI_SUBREAPER=
ENTRYPOINT ["/tini", "-s", "--", "/lambda-entrypoint.sh"]
```

`-s` or `export TINI_SUBREAPER=` was used because without it, tini runs as pid 8 (or anything but not 1)

How to make tini run as pid 1 on AWS Lambda?

**Comment by krallin** [comment]
You should try to work out what PID1 actually is in your container. It’s up
to whatever PID1 is to let you take over as PID1.

Separately, if your environment does not allow registering as a subreaper
there’s very little Tini can do about it I’m afraid.

**Comment by samkit-jain** [comment]
Okay, thanks for the update. Closing this issue then. Will reach out to AWS Support.

**Comment by samkit-jain** [comment]
Hi @f-dig No luck. Pid 1 is reserved in AWS Lambda and it will not work the way it is supposed to. Maybe the situation has changed now but for that you'll have to reach out the AWS support.
