### ISSUE TITLE
Timeout child

### ISSUE THREAD

**Issue by danilobuerger** [krallin/tini#29]
Idea: add a timeout parameter to tini. After timeout is reached, child is exited with != 0 status.

Since most of us are using tini with containers, which can often be of a worker nature, it would be nice to be able to timeout the task so that the container stops.

Current use case for me: I have a dockerized hubot running on ECS as a service which connects to slack. There is an error in the adapter implementation hubot-slack which causes hubot to become unresponsive after some time. If i can timeout hubot, the container would stop, causing ECS to restart the service, causing hubot to reconnect. Which is kind of nice :-).

**Comment by tianon** [comment]
Couldn't this be implemented easily with the "timeout" tool without having tini implement this itself?

ie,
```console
$ docker run -it --rm debian:jessie sh -c 'timeout 5s sleep 10'
$ echo $?
124
$ docker run -it --rm debian:jessie sh -c 'timeout 10s sleep 5'
$ echo $?
0
```

**Comment by danilobuerger** [comment]
Counter example (busybox implementation of timeout):

```
/ # timeout -t 1 sh -c 'sleep 2 && echo foo &'
/ # foo
```

Point being: if the child forks & exits, timeout will exit with status 0.

**Comment by yosifkit** [comment]
Correct, I get that same problem when using `timeout -t 1 sh -c 'sleep 2 && echo foo &'` on debian.  Your example would not run in `tini` in docker anyway since the process that `tini` would be tracking would have exited, making `tini` exit, and thus the container would be destroyed (ie, `docker run -it --rm busybox sh -c 'sleep 10 && echo foo &'` dies immediately, whether or not I use any combination of `tini` and `timeout`).

**Comment by danilobuerger** [comment]
Yeah, i have chosen a bad example there. I will think of another one if necessary.

**Comment by krallin** [comment]
Hey @danilobuerger , thanks for your suggestion!

So, this *feels* a bit more involved that I'd intuitively envision Tini supporting (though that doesn't necessarily mean much... intuition can be wrong!)

But, for what it's worth, I'm working on having pre / post commands in #28 that run (as the name implies) before Tini starts your child and after it exits. 

I think this feature would let you solve this problem without any additional work in Tini. Just point `--pre` to an executable file containing the following script:

```
#!/bin/sh
sh -c 'sleep 10 && echo "TIMEOUT" && kill -s TERM 1' &
```

What do you think? If you want to try it out, the feature's already coded, so you can re-compile Tini and try it now.

Cheers,

**Comment by krallin** [comment]
Now that I think about it, you probably don't even need `--pre` to do this. Just use this as your `ENTRYPOINT` instead of using Tini directly:

```
#!/bin/sh
sh -c 'sleep 10 && echo "TIMEOUT" && kill -s TERM 1' &
exec /tini/tini -- sh -c 'sleep 20'
```

Cheers,

**Comment by danilobuerger** [comment]
Actually, never mind. I had an error in my thinking. Everyone else was correct :-).

**Comment by krallin** [comment]
Glad you sorted this out then : )

**Comment by danilobuerger** [comment]
Just for future reference: @tianon was correct, the timeout will work fine.
