### ISSUE TITLE
32 bit build

### ISSUE THREAD

**Issue by hundeboll** [krallin/tini#30]
Hi,

I am running containers with both 64bit and 32bit binaries for various test purposes. Would you mind building a 32bit release of tini for me to use directly in my Dockerfiles?

It is quite simple to do:

```
cmake . -DCMAKE_C_FLAGS=-m32
make
```

Thanks!

**Comment by krallin** [comment]
Hmm. I'd need to check what happens to the packages that are built. I'm going to be a bit busy this week, so no guarantees as to when I might be able to get to this (sorry!)

Cheers,

**Comment by hundeboll** [comment]
No problems. Thanks for taking a look at this.

**Comment by krallin** [comment]
Hey @hundeboll — is there still interest in this? If so, I can use the same infrastructure set up in to resolve #51 to provide i386 images (see this branch: https://github.com/krallin/tini/commits/i386)

Let me know!

**Comment by timboven** [comment]
Not sure if Hunderboll is still interested - but I'm interested in a 32bit version as well

**Comment by TheLQ** [comment]
Any updates?

**Comment by krallin** [comment]
Hi there; yes, there is progress! 😄  

I've added support for i386 binaries in #73, and they're available in the 0.14 pre-release: https://github.com/krallin/tini/releases/tag/v0.14.0.pre0.

I've already done most of the testing there and I'll be merging this soon, but if you'd like to give them a shot to double-check everything works fine before I merge, now's the time!

Thanks!

**Comment by krallin** [comment]
This is fixed as of 0.14.0 😄

**Comment by hundeboll** [comment]
Cool, I am still interested (once I get around to update my Docker files ...)

Thanks.
