### ISSUE TITLE
Move alpine package to community repos

### ISSUE THREAD

**Issue by danilobuerger** [krallin/tini#31]
@krallin this is just a reminder for me so i don't forget on the next release

**Comment by krallin** [comment]
Sure; thanks @danilobuerger. Does this mean Tini might move from the Alpine testing repo to another one? Let me know if I need to upgrade the README : ).

Cheers,

**Comment by danilobuerger** [comment]
Yes exactly. The repository will change. However since the community repository is active by default, we will not have to specify it anymore. The command will then become:

```
apk add --update tini
```

The community repository was introduced with alpine 3.3, so on next release of tini we should leverage this.

**Comment by krallin** [comment]
Awesome; looking forward to it!

Cheers,
