### ISSUE TITLE
Add gpg signatures to releases

### ISSUE THREAD

**Issue by yosifkit** [krallin/tini#32]
It would be nice to have a couple `.asc` files to be able to verify downloads and make security-concerned people feel better with that extra checkbox on the list :wink:.

**Comment by krallin** [comment]
True! I'll try to get that done shortly : )

**Comment by yosifkit** [comment]
Thanks! :heart:

**Comment by krallin** [comment]
@yosifkit Signed binaries are available as of 0.9.0 : )

Cheers,
