### ISSUE TITLE
Pronunciation 

### ISSUE THREAD

**Issue by farski** [krallin/tini#35]
Lots of debate in the office over this. Is it tini like tiny? Tini like teenie? Something else?

**Comment by farski** [comment]
See also #36

**Comment by danilobuerger** [comment]
Obviously teenie :dancer:

**Comment by kookster** [comment]
You say Teenie, but you imply 'Tiny Dancer' https://www.youtube.com/watch?v=hoskDZRLOCs

I think we need more information.

**Comment by krallin** [comment]
Haha — definitely Tennie :)
