### ISSUE TITLE
Not compatible with alpine 3.3

### ISSUE THREAD

**Issue by Vanuan** [krallin/tini#37]
Dockerfile:

    FROM alpine:3.3
    ENV TINI_VERSION v0.9.0
    ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
    RUN chmod +x /tini

Command:

    ldd /tini

Output:

    /lib64/ld-linux-x86-64.so.2 (0x7fe8969b6000)
    libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fe8969b6000)
    Error relocating /tini: __fprintf_chk: symbol not found

**Comment by Vanuan** [comment]
Ok, tini-static works.

**Comment by krallin** [comment]
Hey @Vanuan, glad you could solve this using tini-static.

The tini binary is built against glibc, so it's not completely a surprise that it would have issues working against Alpine's muslc. This is indeed what tini-static is for.

I'll try to see if there's something I can do do to work around this problem, but in the meantime, thanks to @danilobuerger, there is a tini package for Alpine you can install using `apk`:

    apk add --update --repository http://dl-1.alpinelinux.org/alpine/edge/community/ tini


If you're using Alpine, I'd recommend using the package :)

**Comment by Vanuan** [comment]
> http://dl-1.alpinelinux.org/alpine/edge/community

This is on edge. Could it be added to other versions of apline?

**Comment by krallin** [comment]
@Vanuan,

That's up to the Alpine maintainers, and my understanding is that new packages don't get added after an Alpine version is released (like most distros). So, no, I don't think it can be added to other versions.

That being said, you can install this package on an older version of Alpine without trouble (in other words, you don't need to be on Alpine Edge to use this package, even though it's in the Edge repository).

Cheers,
