### ISSUE TITLE
/tini vs /usr/bin/tini

### ISSUE THREAD

**Issue by JonJagger** [krallin/tini#38]
After installing tini on Alpine via
$ apk add --update --repository http://dl-1.alpinelinux.org/alpine/edge/community/ tini

then tini lives in /usr/bin 
This caught me out for a while because the earlier ADD installation ends
ENTRYPOINT ["/tini", "--"]

Maybe edit the alpine instructions and add...

For example
RUN apk add --update --repository http://dl-1.alpinelinux.org/alpine/edge/community/ tini
ENTRYPOINT ["/usr/bin/tini", "--"]

Many thanks

**Comment by krallin** [comment]
Ugh. Good catch, thanks for the heads up! 

I'll probably just update the instructions to use `/usr/bin` everywhere.

**Comment by JonJagger** [comment]
Good idea.

One other thing I just remembered. I was also caught out because my Dockerfile started
FROM alpine:3.2
I had to edit that to
FROM alpine:edge

Cheers

**Comment by danilobuerger** [comment]
@JonJagger you dont have to use edge to install tini from apk.
```
apk add --update --repository http://dl-1.alpinelinux.org/alpine/edge/community/ tini
``` 

should just work.

**Comment by JonJagger** [comment]
Maybe the repository was temporarily down and with edge it tries a different one as a fall back?

**Comment by Nelyus** [comment]
@danilobuerger @JonJagger  it didn't work for me either but the following did:
```
apk add --update --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ tini
```
(I got it by first trying with alpine:edge, where it does fallback to this one)

**Comment by ncopa** [comment]
`tini` was moved to community repository so it will be available for the v3.4 Alpine release.

I would like to move it from `/usr/bin/tini` to `/sbin/tini` where it belongs, but it will break your docker images again. That said, `edge` repositories is not considered stable, which you already discovered.

Should i bother add a combat /usr/bin/tini symlink?

**Comment by JonJagger** [comment]
Just in /sbin/ is fine by me.
Cheers
Jon

On Wed, May 4, 2016 at 9:44 PM, Natanael Copa <notifications@github.com>
wrote:

> tini was moved to community repository so it will be available for the
> v3.4 Alpine release.
>
> I would like to move it from /usr/bin/tini to /sbin/tini where it
> belongs, but it will break your docker images again. That said, edge
> repositories is not considered stable, which you already discovered.
>
> Should i bother add a combat /usr/bin/tini symlink?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/krallin/tini/issues/38#issuecomment-216997122>
>



-- 
Cyber-Dojo : a place to practise the collaborative game called software
development.
Server at http://www.cyber-dojo.org
Open-sourced at http://github.com/JonJagger/cyberdojo
Explained at http://jonjagger.blogspot.co.uk/p/cyber-dojo_2380.html
Video of Roman Numerals kata in Ruby at https://vimeo.com/104548135

**Comment by krallin** [comment]
Hey @ncopa,

First, thanks a ton for the heads up! I really appreciate it.

> I would like to move it from `/usr/bin/tini` to `/sbin/tini` where it belongs, but it will break your docker images again. That said, edge repositories is not considered stable, which you already discovered.

I'm assuming users that are installing via `apk add --update --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ tini` will also be affected, right? 

> Should i bother add a combat /usr/bin/tini symlink?

My README doesn't indicate the full path for Alpine, but there's definitely a number of Alpine / Tini users that have installed Tini via apk and that are currently using the full path to hit it: https://github.com/search?utf8=%E2%9C%93&q=%22%2Fusr%2Fbin%2Ftini%22+apk&type=Code&ref=searchresults  (of course, there might also be some users this search doesn't find, or who don't host their Dockerfile in a public GitHub repo).

I would definitely prefer not breaking their builds. Is adding a symlink something you've done for other packages in the past? 

Let me know if I can help in any way.

Thanks again!

**Comment by ncopa** [comment]
@krallin I have made symlinks in the past for compatibility. But if I add the combat symlink for the v3.4 release, then i am afraid that people will keep the `/usr/bin/tini` and we will end up supporting both for eternity.

I think I´ll just move it to `/sbin` so it gets correct from v3.4 and forward. As mentioned, I also think it is important to know that things in `edge` repositories are not considered stable, so people who gets bitten by this can also adjust their repo to stable repo while at it.

I am also open for back porting `tini` to v3.3 (current stable). But then it will also be as `/sbin/tini`.

**Comment by krallin** [comment]
@ncopa I understand your concern about never being able to deprecate it — as a middle ground, could we perhaps add a shell script in `/usr/bin/tini` prompting users to update before `/usr/bin/tini` goes away?

Something like the following might work:

```
#!/bin/sh
echo 'WARNING: Tini has been relocated to /sbin/tini.
Please update your scripts to use /sbin/tini going forward.
/usr/bin/tini has been preserved for backwards compatibility in Alpine 3.4,
but will be removed in Alpine 3.5.' >&2

exec /sbin/tini "$@"
```

(I reckon one can also indicate that `edge` isn't stable in there)

**Comment by ncopa** [comment]
@krallin sounds like a good idea. I´ll do this.

**Comment by krallin** [comment]
Thanks so much @ncopa, I really appreciate it :)

**Comment by megastef** [comment]
When do you release 3.4 with tiny?

**Comment by ncopa** [comment]
alpine 3.4 is supposed to be released in May 2016.
