### ISSUE TITLE
"I have no name!" as user logging into docker container using tini

### ISSUE THREAD

**Issue by rcbop** [krallin/tini#41]
Hey there, this feels more like a question then a bug.
I'm currently using a Jenkins instance inside a docker container. 
This image happens to use Tini as PID 1. 
When I try open a shell into it with:

`docker exec -it jenkins /bin/bash`

I get this as username:

`I have no name!@<container_id_hash>:/$`

This is keeping me from using shell born ssh commands from Jenkins jobs that run in this container:

`$ ssh`
`No user exists for uid 497`

`$ id`
`$ uid=497 gid=495 groups=495`

I tried creating an user for that uid in /etc/passwd and also a group for that gid in /etc/group but it was a no deal!

I'm only able to run ssh manually if I login as jenkins user like this:

`docker exec -it --user=jenkins jenkins /bin/bash`

I could circle around that using ssh related plugins. But I'm really curious to understand why this happens only with docker images that use Tini as ENTRYPOINT.

**Comment by krallin** [comment]
Hi there @rcbop,

What image are you using for Jenkins? The official one, or a hand-rolled one? If the latter, can you share your `Dockerfile`? Either way, can you share how it was started?

I doubt this is due to Tini itself, considering it doesn't do anything UID-related, but I'm happy to look into it a little bit.

Cheers,

**Comment by rcbop** [comment]
Hey there @krallin!
My dockerfile for that container is currently something like this:

    FROM jenkinsci/jenkins:2.3
    USER root
    RUN apt-get update -qqy \
        && apt-get install -y \
          locales \
          nano \
          make \
          openssh-client \
        && locale-gen en_US.UTF-8 \
        && echo "LC_ALL=en_US.UTF-8" >> /etc/environment \
        && echo "LANG=en_US.UTF-8" >> /etc/environment \
        && echo "LC_ALL=en_US.UTF-8" >> /etc/default/locale \
        && echo "LANG=en_US.UTF-8" >> /etc/default/locale
    
     // a few credentials related stuff [...]

    USER jenkins
    ENV JAVA_OPTS="-Dfile.encoding=UTF8"
    //Installing plugins
    COPY plugins.txt /usr/share/jenkins/plugins.txt
    COPY executors.groovy /usr/share/jenkins/ref/init.groovy.d/executors.groovy
    RUN /usr/local/bin/plugins.sh /usr/share/jenkins/plugins.txt

Thank you for the awesomness!

**Comment by krallin** [comment]
@rcbop, `jenkinsci/jenkins:2.3` doesn't actually exist. I'm assuming you might be using `jenkins:2.3`? If not, it's going to be a little hard for me to try and repro.

Using `jenkins:2.3`, I'm able to spin up a new container and use `docker exec` with it and I don't get the `I have no name!` error. I suspect this issue might be related to the base image you're using (perhaps it's outdated?), or perhaps you're using Docker with user namespace support and something's going wrong?

Either way, do you have a reason to think this only happens when Tini is used?

**Comment by rcbop** [comment]
Hey @krallin. No particular reason, except, I guess, my lack of understanding of how Tini works. I'm gonna try studying the code. Thanks for the support, by the way, here is [jenkinsci/jenkins](https://hub.docker.com/r/jenkinsci/jenkins/) dockerhub page which is different from official docker [page for jenkins](https://hub.docker.com/_/jenkins/). Cheers.

**Comment by rcbop** [comment]
I have moved this to a stackoverflow question in [hope](http://stackoverflow.com/questions/37836124/i-have-no-name-as-user-logging-into-jenkins-in-a-docker-container-that-uses-t) to reach more people.

**Comment by krallin** [comment]
@rcbop Ha; it looks like [the 2.3 tag doesn't exist there (anymore?)](https://hub.docker.com/r/jenkinsci/jenkins/tags/). 

Could you perhaps try with another one of their tags and let me know which one you chose and whether it works? That way at least we'll be working off of the same base image.

Cheers,

**Comment by rcbop** [comment]
Whoa.. true to that... I'm gonna check that and report my finds. Thanks for pointing that out.

**Comment by rcbop** [comment]
Hey @krallin, 

I have come across the information that this message is displayed when the current user's uid and gid from docker host is not mapped inside the container's `/etc/passwd`. So Tini is not the cause of that. So I'm closing this issue. Thanks for all the support.

**Comment by krallin** [comment]
Thanks for confirming :+1:

**Comment by MRCO-DURON** [comment]
I have had this same issue but in a Docker container running on Kubernetes. I removed the security context section from the deployment and the respective user declared. 
After this, the issue was gone.
