### ISSUE TITLE
Using CURL instead of ADD

### ISSUE THREAD

**Issue by davidbarton** [krallin/tini#52]
Best practice says avoid ADD where you can and use CURL for adding remote files. Should tini do the same and provide basic usage example without ADD? See https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#/add-or-copy

**Comment by krallin** [comment]
Using `curl` is discouraged if you're pulling a package that you're about to extract (emphasis mine):

> Because image size matters, using ADD to fetch **packages** from remote URLs is strongly discouraged; you should use curl or wget instead. That way **you can delete the files you no longer need after they’ve been extracted** and you won’t have to add another layer in your image.

But that's not the case here. 

In the example provided in the README, we're fetching a binary that we intend to keep (except in the case of fetching the signature; but it's a tiny file, so I don't think adding a dependency on curl for this is valuable). 

Adding curl would add a dependency for install Tini, which isn't strictly needed, and add complexity to a README that's supposed to contain the minimal instructions to get you started. I don't think that's a positive change.

---

That being said, if you absolute want to use curl, you can of course do so! :smile:. Here's what you need:

```
ENV TINI_VERSION=0.9.0
RUN curl -fsSL "https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini" -o /tini \
 && curl -fsSL "https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini.asc" -o /tini.asc \
 && export GNUPGHOME="$(mktemp -d)" \
 && gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 0527A9B7 \
 && gpg --batch --verify /tini.asc /tini \
 && rm -rf "$GNUPGHOME" /tini.asc \
 && chmod +x /tini
```

(from https://github.com/krallin/tini/issues/43)

**Comment by davidbarton** [comment]
Make sense, thanks! I love you included the curl usage example.

**Comment by krallin** [comment]
You're welcome!
