### ISSUE TITLE
Build for tini-static fails on centos 7

### ISSUE THREAD

**Issue by KurtStam** [krallin/tini#53]
When running cmake . && make I run into

cmake . && make 
-- The C compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kstam/git/tini
Scanning dependencies of target tini
[ 50%] Building C object CMakeFiles/tini.dir/src/tini.c.o
Linking C executable tini
[ 50%] Built target tini
Scanning dependencies of target tini-static
[100%] Building C object CMakeFiles/tini-static.dir/src/tini.c.o
Linking C executable tini-static
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
make[2]: *** [tini-static] Error 1
make[1]: *** [CMakeFiles/tini-static.dir/all] Error 2
make: *** [all] Error 2

Any hints on how to go about fixing this?
Thx!

**Comment by krallin** [comment]
You're probably missing `yum install glibc-static`

(see http://stackoverflow.com/questions/16024978/usr-bin-ld-cannot-find-lc-while-compiling-with-makefile)

**Comment by KurtStam** [comment]
yup that was it. Thx for your quick reply.

**Comment by krallin** [comment]
No problem!
