### ISSUE TITLE
Publish build process / support fedora ?

### ISSUE THREAD

**Issue by thekad** [krallin/tini#76]
Hello,

I looked around but couldn't find the process you used to build the centos image found in the docker hub, and I am interested in using it in fedora linux. So if you have either a) a build process I can piggy back on or b) publish a fedora docker image that would be extremely helpful :)

**Comment by krallin** [comment]
Hi there,

The builds happen here: https://github.com/krallin/tini-images/ — it's basically a set of Dockerfiles in `autogen` that are auto-generated from source files in `src`. There's basically a handful of  scripts that must be provided for each platform. 

I can try and take a look at Fedora, but I don't have much experience with dnf, so this might take a little time to get right.

**Comment by thekad** [comment]
Thanks!
