### ISSUE TITLE
Config option to set the tini_VERSION_GIT at build time

### ISSUE THREAD

**Issue by ncopa** [krallin/tini#79]
Docker now uses tini in the official release. Docker will check for a given git version string from tini and complain if it does not match with the given git revision. This means that if you build tini from a tarball generated from the exact required git revision, the current tini CMakeLists.txt will not detect the git revision correctly and docker will end up unhappy with the correct version of tini.

To fix this I propose that you can at build time set the `tini_VERSION_GIT` as a cmake config option.

For more details why this is needed, please see https://github.com/alpinelinux/aports/pull/1123

**Comment by ncopa** [comment]
Something like this, but maybe also let it override if `git_version_check_ret` is 0.

````diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 8936f18..c031179 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -8,6 +8,8 @@ set (tini_VERSION_PATCH 0)

 # Build options
 option(MINIMAL "Disable argument parsing and verbose output" OFF)
+option(TINI_GIT "Override the git revision string" "")
+

 if(MINIMAL)
        add_definitions(-DTINI_MINIMAL=1)
@@ -33,7 +35,7 @@ if("${git_version_check_ret}" EQUAL 0)
     set(tini_VERSION_GIT "${tini_VERSION_GIT}-dirty")
   endif()
 else()
-  set(tini_VERSION_GIT "")
+  set(tini_VERSION_GIT "${TINI_GIT}")
 endif()

 # Flags
````

**Comment by krallin** [comment]
:+1: - see #80

**Comment by gena01** [comment]
Just for reference to what docker is doing internally: https://github.com/docker/docker/blob/master/daemon/info_unix.go#L58

**Comment by krallin** [comment]
Thanks @gena01 - it looks like with #80, setting `TINI_GIT` to the full hash you expect (or any subset, really) should work here.

Perhaps you could test using `https://codeload.github.com/krallin/tini/zip/git-override`?

Thanks!

**Comment by yosifkit** [comment]
This seems like a fix for a bug in the wrong place. Docker is the one looking for a commit string in another project. This makes packaging docker and docker's dependencies harder (ex. the alpine issue this stems from).  Tini is a fairly stable cli interface. Docker should mostly be fine with any version `>0.11.0`

**Comment by krallin** [comment]
Thanks @yosifkit!

I'll defer to you and @ncopa regarding what the best approach is here: I'm happy to carry the changes proposed in #80 if needed, but if that problem can be solved without any changes in Tini, then that's even better 😄

**Comment by gena01** [comment]
@yosifkit yes, docker should not be so tightly bound to a tini commit, but the current CMakeLists.txt produces different version output when compiled from "git clone" vs a release archive (which we trying to fix).

**Comment by tianon** [comment]
I've been seeing warnings in my Docker daemon logs for this too -- I think
this is a bug in Docker, so I'm going to send a PR to Docker to adjust that
logic to handle the two different ways the Tini version output comes out,
because this seems odd to fix in Tini.

**Comment by tianon** [comment]
I've filed https://github.com/docker/docker/pull/32187 to relax Docker's `tini --version` parsing a bit. :+1:

**Comment by krallin** [comment]
Assuming we're good here; let me know if not :)

**Comment by tonylambiris** [comment]
@krallin My apologies for commenting on a closed issue, but I can't seem to get VERSION_GIT working:

```
11:42:49 holodeck (master) ~/Documents/Git/tini $ cmake -DVERSION_GIT=949e6fa . 
-- The C compiler identification is GNU 7.1.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test HAS_BUILTIN_FORTIFY
-- Performing Test HAS_BUILTIN_FORTIFY - Failed
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    VERSION_GIT


-- Build files have been written to: /home/tlambiris/Documents/Git/tini
11:42:57 holodeck (master) ~/Documents/Git/tini $ make 
Scanning dependencies of target tini-static
[ 25%] Building C object CMakeFiles/tini-static.dir/src/tini.c.o
[ 50%] Linking C executable tini-static
[ 50%] Built target tini-static
Scanning dependencies of target tini
[ 75%] Building C object CMakeFiles/tini.dir/src/tini.c.o
[100%] Linking C executable tini
[100%] Built target tini
11:43:07 holodeck (master) ~/Documents/Git/tini $ ./tini --version
tini version 0.15.0 - git.4892d4d
```

Am I missing something ridiculously obvious? The main issue (like other people) is what is expected output from docker:
```
# docker info 2>/dev/null | grep init
Init Binary: /usr/libexec/docker/docker-init
init version: v0.13.0 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
```

This behavior is from a docker package builder that is heavily hacked from `docker-latest` in [koji](https://koji.fedoraproject.org/koji/packageinfo?packageID=23075). I've managed to get the other runtime executables working, ie:

```
# build docker-runc
pushd runc-%{commit_runc}
make COMMIT=%{commit_runc} BUILDTAGS="seccomp selinux"
popd

# build docker-containerd
pushd containerd-%{commit_containerd}
make GIT_COMMIT=%{commit_containerd}
popd

# build docker-init
pushd tini-%{commit_init}
cmake -DMINIMAL=ON .
make tini-static
popd
```

Any pointers would be greatly appreciated!

**Comment by krallin** [comment]
@tonylambiris this was never merged: Docker implemented https://github.com/moby/moby/pull/32187, which made this somewhat irrelevant. What's your use case here?

**Comment by krallin** [comment]
To be clear, I'm not against re-opening if this turns out to be needed, but I'd like to understand why first 😄

**Comment by tonylambiris** [comment]
@krallin I suppose the use-case here would be for consistency's sake. Since all external docker dependencies are grabbed via a tarball archive from github, there is no `.git` directory available -- with building RPM's you mostly only have the commit hash of the repo you want.

Like the examples for `docker-containerd` and `docker-runc`, overriding the commit is definitely a hack but at least the option is there to ensure expected commit hashes. It's much easier to debug docker issues (considering all the recent activity with them) when a 1:1 match can be immediately ascertained versus expectations that usually involves manually tracing execution paths.

Sorry if I'm being a pain, it would really make the world a better place so all dev's packaging/shipping docker packages will have docker-init pinned to what dockerd is expecting.

**Comment by krallin** [comment]
@tonylambiris sorry, I think you might have overlooked my question here: my understanding is that with the Docker PR that I linked to above, Docker no longer cares about the exact commit hash for Tini, and is OK with having just the version. Is that incorrect? (in the example above, it seems like if you set `commit_init` to `v0.13.0`, Docker should be happy with it?)

Alternatively, is the problem completely unrelated, in the sense that while Docker is fine with just the version, _you_ would really rather have the exact commit hash?

Could you also clarify where `commit_init` comes from?

---

I'm sorry if it seems like I'm being a little obtuse here. I'm really not against finally adding this, but you seem to have a lot more context about this than I do, and I'm a lost trying to follow you here.

**Comment by tonylambiris** [comment]
@krallin No problem, I appreciate your time and feedback.

I suppose the issue isn't so much of docker being able to more gracefully parse version output of executables that live in `/usr/libexec/docker` as it is matching on what the docker daemon expects.

To me what's important is that for each docker branch that has been tagged,
