### ISSUE TITLE
Explain docker-init and tini relationship

### ISSUE THREAD

**Issue by schlomo** [krallin/tini#85]
Hi noticed that docker ships tini [since version 1.13](https://github.com/moby/moby/blob/master/CHANGELOG.md) - congratulations!

I think it would help your users and others who happen to find this repo if you would mention this fact in the `README.md` file and also mention how to use tini with docker without installing it (simply add `--init` to the `docker run` call.

**Comment by krallin** [comment]
Good call; thanks!
