### ISSUE TITLE
Unexpected error forwarding signal on Travis-CI

### ISSUE THREAD

**Issue by parente** [krallin/tini#9]
When attempting to spawn a docker container on Travis CI where tini is the entrypoint to the container, I'm seeing:

`[FATAL] Unexpected error when forwarding signal: 'Permission denied'`

which appears to originate from https://github.com/krallin/tini/blob/master/src/tini.c#L249

Here's an example log from Travis:

* .travis.yml file: https://github.com/parente/kernel_gateway/blob/travis/.travis.yml
* Log from travis: https://travis-ci.org/jupyter-incubator/kernel_gateway#L36
* Container definition using tini as entrypoint: https://github.com/jupyter/docker-stacks/blob/master/minimal-notebook/Dockerfile#L68

I'm not sure if this is a bug in tini or just a constraint of how Travis is executing the containers. Is there some CAP that tini requires that maybe Travis is not allowing? If so, it would be good to document it  here.

Ref jupyter-incubator/kernel_gateway#15

**Comment by krallin** [comment]
Thanks for the report. I'm looking into this.

Tini does need to be able to pass signals on to its child process. This may be a problem, especially if your child process is running as a different user. I'll try and reproduce your issue. 

It looks like `start-notebook.sh` changes user, so if you're up for it, it might make sense to start Tini itself in `start-notebook.sh` (in your `exec` line) to run Tini as the same user as the rest of your stuff.

Cheers,

**Comment by parente** [comment]
Thanks for the quick feedback. After I filed this, I tracked down travis-ci/travis-ci/issues/4751 which suggests `--privileged` as a quickfix and makes it look like certain caps limits are being set on travis.

The problem does go away with --privileged so I don't think there's anything wrong here. Will close.

(For the record in case others happen upon this: I switched to not using Docker at all because after fixing the signal issue, I hit other problems with my tornado tests failing mysteriously within the container: https://travis-ci.org/jupyter-incubator/kernel_gateway/builds/85342979 in container vs https://travis-ci.org/jupyter-incubator/kernel_gateway/builds/85345398 outside container.)

**Comment by krallin** [comment]
Thanks for the heads up, @parente. 

I'll try and add some documentation explaining the permissions that Tini (or anything that does zombie reaping and signal forwarding, really) needs to run. 

Cheers,

**Comment by oliv3r** [comment]
@krallin did you ever add this documentation somewhere? I can't find anything in the main 'readme' and bumped into the dreaded
```
[FATAL tini (1)] Unexpected error when forwarding signal: 'Operation not permitted'
```
where I have the following in my compose
```yaml
    init: true
    cap_add:
      - dac_read_search
      - setgid
      - setuid
    cap_drop:
      - all
```

I'd be more then happy to add the missing permissions (am I? :p) but I'd like to know which ones of course.

**Comment by oliv3r** [comment]
Update: It seems it _might_ be as simple as  `kill` signal!
