### ISSUE TITLE
Unable to build for amd64 machine

### ISSUE THREAD

**Issue by ghadimani21** [krallin/tini#94]
I am building tini on amd64 machine
My go env as follow:
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ravi/gopath"
GORACE=""
GOROOT="/usr/lib/go-1.6"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

on executing command 
$sudo ./ci/install_deps.sh
[sudo] password for test:
+ DEPS=(build-essential git gdb valgrind cmake rpm python-dev libcap-dev python-pip python-virtualenv hardening-includes gnupg)
./ci/install_deps.sh: line 12: ARCH_SUFFIX: unbound variable

Can anyone please guide me on this?

**Comment by krallin** [comment]
The scripts under `./ci` are here to run in CI, they aren't meant to be used if you just want to build Tini locally. To build locally, use [the instructions found in the README](https://github.com/krallin/tini#building-tini):

```
cmake . && make
```

You'll need to install  `cmake`, `make` and a C compiler to run this successfully.

Cheers,
